import type { AppLocale } from '@/i18n/locale'

export const CGV_EFFECTIVE_DATE = '2026-09-23'

export const seller = {
  name: 'BOUKIR DIAMOND CONSTRUCTION STORE',
  form: 'SARL',
  capital: '100 000,00 DH',
  rc: '142631/TANGER',
  if: '54023456',
  ice: '003381011000082',
  address: 'IKAMAT REDOUAN 1, AZIB HAJ KADDOUR, LOCAL 1 ET N° 2, TANGER, MAROC',
  email: 'boukir.diamond23@gmail.com',
  mobile: '06 50 81 28 94',
  phone: '06 66 21 66 57',
} as const

type Section = readonly [title: string, body: string]

type CgvCopy = {
  title: string
  intro: string
  updated: string
  legalIdentity: string
  labels: readonly [string, string, string, string, string, string, string, string, string]
  sections: readonly Section[]
}

export const cgvContent: Record<AppLocale, CgvCopy> = {
  fr: {
    title: 'Conditions générales de vente',
    intro: 'Ces conditions régissent les achats de produits effectués sur boukirdiamond.com. Elles précisent notamment les règles de commande, de livraison, de rétractation et de garantie.',
    updated: 'En vigueur depuis le 23 septembre 2026',
    legalIdentity: 'Identification du vendeur',
    labels: ['Raison sociale', 'Forme juridique', 'Capital social', 'Registre de commerce', 'Identifiant fiscal', 'ICE', 'Adresse', 'E-mail', 'Téléphone'],
    sections: [
      ['1. Vendeur et contact', 'Le site boukirdiamond.com est exploité par BOUKIR DIAMOND CONSTRUCTION STORE, qui vend notamment des matériaux de construction, du carrelage, du marbre et des produits connexes. Les coordonnées complètes du vendeur figurent ci-dessus.'],
      ['2. Objet et champ d’application', 'Ces conditions s’appliquent aux commandes de produits passées sur la boutique en ligne. La version acceptée lors de la confirmation de la commande est applicable à celle-ci. Les droits impératifs des consommateurs restent acquis. Les prestations de maâlems ou de tiers ne sont pas couvertes par ces conditions, sauf mention expresse.'],
      ['3. Acceptation des conditions', 'Avant de confirmer, le client peut vérifier le contenu de son panier, les prix, les frais éventuels, le mode de paiement et l’adresse de livraison, puis corriger les erreurs. La confirmation de la commande emporte acceptation des présentes conditions et obligation de payer le montant indiqué, sous réserve des droits prévus par la loi.'],
      ['4. Produits', 'Les caractéristiques essentielles, références, dimensions et unités disponibles sont indiquées sur les fiches produits. Les photos et couleurs sont indicatives : les écrans, l’éclairage et les lots de fabrication peuvent entraîner de légères variations. Pour les matériaux naturels, des différences usuelles de teinte ou de veinage peuvent exister, sans préjudice des droits liés à une non-conformité réelle. Le client vérifie l’adéquation du produit et les quantités nécessaires avant de commander.'],
      ['5. Prix', 'Les prix sont affichés en dirhams marocains, toutes taxes applicables comprises sauf indication claire contraire. Les frais de livraison et autres frais sont communiqués avant la confirmation. Le prix dû est celui du récapitulatif validé par le client. En cas d’erreur matérielle manifeste signalée avant l’exécution, le client peut accepter le prix corrigé ou annuler sa commande et obtenir le remboursement des sommes versées. Les promotions valent pendant leur durée et dans la limite des stocks.'],
      ['6. Commande et formation du contrat', 'Le client choisit les produits, vérifie son panier, renseigne ses coordonnées, choisit la livraison ou le retrait et le paiement, puis confirme après lecture du récapitulatif. Un accusé de réception indique les éléments essentiels et le numéro de commande. L’exécution reste soumise à la disponibilité des produits, à l’exactitude des informations et, le cas échéant, à la validation du paiement. Une commande peut être suspendue en présence de données incomplètes ou d’un soupçon sérieux de fraude.'],
      ['7. Disponibilité', 'Les commandes sont acceptées dans la limite des stocks. Si un produit devient indisponible après confirmation, le vendeur informe rapidement le client. Celui-ci peut accepter expressément un produit de remplacement, convenir d’un nouveau délai ou annuler la partie concernée ou toute la commande. Les sommes payées pour le produit indisponible sont remboursées conformément aux délais légaux. Aucun remplacement n’est imposé sans accord du client.'],
      ['8. Paiement', 'Les moyens de paiement réellement proposés sont ceux affichés au moment de la commande et peuvent varier selon le produit, la zone et le client. Un virement bancaire n’est considéré reçu qu’après encaissement effectif, sauf accord écrit différent. Les paiements électroniques sont traités par les prestataires indiqués au client ; le vendeur ne conserve pas les données bancaires confidentielles complètes traitées directement par ces prestataires.'],
      ['9. Livraison', 'La livraison est proposée dans les zones desservies au Maroc, à l’adresse complète fournie par le client. Les frais et le délai estimatif sont communiqués avant validation lorsque cela est possible. À défaut d’un autre délai convenu, l’exécution intervient dans le délai légal maximal de trente jours à compter de la confirmation de réception de la commande. En cas de retard important, le vendeur contacte le client pour proposer une solution conforme à ses droits. À la réception, il est conseillé de vérifier les colis et de signaler rapidement toute casse, erreur ou quantité manquante, avec photos si possible ; l’absence de réserve ne supprime pas les droits impératifs du client.'],
      ['10. Retrait en magasin', 'Lorsque le retrait est proposé, le client choisit le point de retrait et attend la notification de disponibilité avant de se déplacer. Le numéro de commande et une pièce d’identité peuvent être demandés, ainsi qu’une autorisation pour un tiers. La durée de conservation est communiquée avec la commande ou l’avis de mise à disposition.'],
      ['11. Annulation avant expédition', 'Le client peut demander l’annulation avant expédition ou avant le début de la préparation d’un produit personnalisé, en contactant le vendeur. Si l’expédition ne peut plus être arrêtée, les dispositions relatives à la rétractation et aux retours s’appliquent, sans limiter les droits légaux.'],
      ['12. Droit de rétractation', 'Conformément à la loi marocaine n° 31-08, le consommateur dispose en principe de sept jours à compter de la réception pour se rétracter d’un achat à distance, sans motif ni pénalité. Le délai peut être porté à trente jours si les informations requises ne sont pas confirmées par écrit dans les cas prévus par la loi. La demande doit être formulée clairement avant l’expiration du délai, avec le numéro de commande et le produit concerné, à boukir.diamond23@gmail.com ou par un moyen permettant d’en établir la réception. Les modalités de retour sont convenues avec le service client. Les frais de retour sont à la charge du consommateur, sauf erreur du vendeur, défaut ou non-conformité, ou prise en charge annoncée. Le remboursement des sommes dues intervient sans retard et dans le délai légal applicable.'],
      ['13. Exceptions à la rétractation', 'Sous réserve de la loi, le droit de rétractation peut être exclu notamment pour les biens fabriqués, coupés ou personnalisés selon les spécifications du client, les biens qui ne peuvent par nature être réexpédiés, les biens périssables et certaines prestations commencées avec l’accord du consommateur. Une exception applicable est signalée avant la commande.'],
      ['14. Produits défectueux ou non conformes', 'En cas de produit endommagé, erroné, incomplet ou présentant un défaut couvert par la garantie légale, le client contacte rapidement le service client en indiquant son numéro de commande et, si possible, des photos. Après vérification, le vendeur propose la solution prévue par la loi : remplacement, réparation, complément, réduction ou remboursement selon le cas. Les garanties légales, notamment contre les vices cachés, restent applicables indépendamment de toute garantie commerciale.'],
      ['15. Réclamations et service après-vente', 'Toute question relative à une commande, une livraison, un retour ou une garantie peut être adressée à boukir.diamond23@gmail.com ou aux numéros indiqués ci-dessus. Pour faciliter le traitement, le client précise le numéro de commande, ses coordonnées et le problème rencontré, avec les justificatifs utiles.'],
      ['16. Responsabilité et force majeure', 'Le vendeur répond de la bonne exécution de ses obligations dans les limites de la loi, y compris lorsque des prestataires interviennent pour son compte. Il ne peut être tenu responsable d’une inexécution imputable exclusivement au client, à un tiers imprévisible et insurmontable ou à un cas de force majeure reconnu par le droit marocain. Aucune clause ne supprime les droits impératifs du client.'],
      ['17. Compte et données personnelles', 'Le client fournit des informations exactes, protège ses identifiants et signale rapidement tout usage non autorisé. Les données nécessaires au compte, à la commande, au paiement, à la livraison et au service après-vente sont traitées conformément à la loi marocaine n° 09-08 et à la politique de confidentialité publiée sur le site.'],
      ['18. Propriété intellectuelle', 'Les marques, logos, textes, photos, bases de données et éléments du site sont protégés. Leur réutilisation commerciale sans autorisation préalable est interdite, sous réserve des exceptions prévues par la loi.'],
      ['19. Preuve et archivage', 'Les confirmations, données de commande et de paiement et échanges conservés de manière fiable peuvent servir de preuve conformément au droit marocain, sans priver le client de tout autre moyen de preuve recevable. Le client peut consulter ses commandes dans son compte lorsque cette fonction est disponible ou en demander une copie au service client.'],
      ['20. Modification des conditions', 'Le vendeur peut actualiser ces conditions. Une nouvelle version indique sa date d’entrée en vigueur et ne s’applique pas rétroactivement aux commandes déjà confirmées, sauf exigence légale impérative.'],
      ['21. Divisibilité', 'Si une clause est déclarée invalide ou inapplicable, les autres clauses restent en vigueur dans la mesure permise par la loi.'],
      ['22. Droit applicable et litiges', 'Les présentes conditions sont soumises au droit marocain. Le client est invité à adresser d’abord une réclamation écrite au service client afin de rechercher une solution amiable. À défaut, le litige relève des autorités ou juridictions compétentes conformément aux règles légales, sans priver le consommateur de la protection impérative qui lui est reconnue.'],
      ['23. Entrée en vigueur', 'Ces conditions entrent en vigueur le 23 septembre 2026 et remplacent toute version antérieure relative aux ventes de produits sur boukirdiamond.com.'],
    ],
  },
  ar: {
    title: 'الشروط العامة للبيع عبر الإنترنت',
    intro: 'تنظم هذه الشروط شراء المنتجات عبر موقع boukirdiamond.com، وتوضح قواعد الطلب والأداء والتسليم والتراجع والضمان.',
    updated: 'سارية ابتداءً من 23 شتنبر 2026',
    legalIdentity: 'هوية البائع',
    labels: ['الاسم القانوني', 'الشكل القانوني', 'رأس المال', 'السجل التجاري', 'المعرّف الضريبي', 'المعرّف المشترك للمقاولة', 'العنوان', 'البريد الإلكتروني', 'الهاتف'],
    sections: [
      ['1. هوية البائع والاتصال', 'يُشغّل موقع boukirdiamond.com من طرف BOUKIR DIAMOND CONSTRUCTION STORE، المختص في بيع مواد البناء والسيراميك والرخام والمنتجات المرتبطة بها. ترد البيانات القانونية ووسائل الاتصال الكاملة أعلاه.'],
      ['2. موضوع الشروط ونطاقها', 'تسري هذه الشروط على طلبات المنتجات عبر المتجر الإلكتروني، وتطبق النسخة التي قبلها العميل عند تأكيد طلبه. تظل الحقوق الإلزامية للمستهلك محفوظة. ولا تشمل خدمات المعلمين أو خدمات الأطراف الثالثة إلا بنص صريح.'],
      ['3. قبول الشروط', 'قبل التأكيد، يمكن للعميل مراجعة المنتجات والكميات والأسعار والمصاريف وطريقة الأداء وعنوان التسليم وتصحيح الأخطاء. ويعد تأكيد الطلب قبولاً لهذه الشروط والتزاماً بأداء المبلغ المعروض، مع مراعاة الحقوق المقررة قانوناً.'],
      ['4. المنتجات', 'تُعرض الخصائص والمراجع والمقاسات والوحدات الأساسية المتاحة في صفحات المنتجات. الصور والألوان توضيحية وقد تختلف قليلاً بحسب الشاشة أو الإضاءة أو دفعة التصنيع. وقد تظهر في المواد الطبيعية فروق معتادة في اللون أو العروق، دون مساس بحقوق العميل عند عدم المطابقة. على العميل التحقق من ملاءمة المنتج والكميات المطلوبة قبل الطلب.'],
      ['5. الأسعار', 'تعرض الأسعار بالدرهم المغربي، شاملة للضرائب المطبقة ما لم يذكر خلاف ذلك بوضوح. تظهر مصاريف التوصيل والرسوم الأخرى قبل تأكيد الطلب. السعر المستحق هو الوارد في الملخص الذي أكده العميل. عند اكتشاف خطأ مادي ظاهر قبل التنفيذ، يمكن للعميل قبول السعر المصحح أو إلغاء الطلب واسترجاع ما دفعه. تسري العروض في مدتها وفي حدود المخزون.'],
      ['6. الطلب وتكوين العقد', 'يختار العميل المنتجات، ويراجع السلة، ويدخل بياناته، ويختار التسليم أو السحب ووسيلة الأداء، ثم يؤكد بعد مراجعة الملخص. يتوصل بإشعار يتضمن المعلومات الأساسية ورقم الطلب. يبقى التنفيذ رهيناً بالتوفر وصحة المعلومات ونجاح الأداء عند الاقتضاء. ويمكن تعليق الطلب إذا كانت البيانات ناقصة أو وُجد اشتباه جدي في الاحتيال.'],
      ['7. توفر المنتجات', 'تُقبل الطلبات في حدود المخزون. إذا تعذر توفير منتج بعد التأكيد، يُخبر البائع العميل سريعاً، ويمكنه الموافقة صراحة على بديل، أو قبول أجل جديد، أو إلغاء الجزء المعني أو الطلب كله. تُرد المبالغ المؤداة عن المنتج غير المتوفر وفق الآجال القانونية، ولا يُفرض بديل دون موافقة العميل.'],
      ['8. وسائل الأداء', 'وسائل الأداء المتاحة فعلياً هي المعروضة عند إتمام الطلب وقد تختلف بحسب المنتج والمنطقة والعميل. لا يعد التحويل البنكي متوصلاً به إلا عند قيد المبلغ فعلياً، ما لم يتفق كتابة على غير ذلك. يعالج مقدمو الخدمة المبينون للعميل الأداء الإلكتروني، ولا يحتفظ البائع ببيانات البطاقة السرية الكاملة المعالجة لديهم مباشرة.'],
      ['9. التوصيل', 'يتم التوصيل داخل المناطق المخدومة بالمغرب إلى العنوان الكامل الذي يقدمه العميل. تُعرض المصاريف والأجل التقديري قبل التأكيد متى أمكن. ما لم يُتفق على أجل آخر، ينفذ الطلب داخل الأجل القانوني الأقصى، ثلاثين يوماً من تأكيد التوصل بالطلب. عند التأخير الجوهري يتواصل البائع مع العميل لإيجاد حل يحفظ حقوقه. يُنصح بفحص الطرود عند الاستلام وإبلاغ البائع سريعاً بأي كسر أو نقص أو خطأ مع صور إن أمكن؛ ولا يسقط غياب التحفظ حقوق العميل الإلزامية.'],
      ['10. السحب من المتجر', 'إذا توفر خيار السحب، يختار العميل نقطة السحب وينتظر إشعار الجاهزية قبل التوجه إليها. يمكن طلب رقم الطلب ووثيقة تعريف، أو تفويض عند السحب من طرف شخص آخر. تُبلغ مدة الاحتفاظ بالطلب عند تأكيده أو في إشعار الجاهزية.'],
      ['11. إلغاء الطلب قبل الشحن', 'يمكن طلب الإلغاء قبل الشحن أو قبل بدء إعداد منتج مخصص، بالتواصل مع البائع. إذا تعذر إيقاف الشحن، تُطبق قواعد التراجع والإرجاع دون الحد من الحقوق القانونية.'],
      ['12. حق التراجع', 'وفق القانون المغربي رقم 31.08، يحق للمستهلك من حيث المبدأ التراجع عن شراء عن بعد خلال سبعة أيام من استلام المنتج دون تبرير أو غرامة. وقد يمتد الأجل إلى ثلاثين يوماً عند عدم تأكيد المعلومات المطلوبة كتابة في الحالات القانونية. يرسل العميل تصريحاً واضحاً قبل انتهاء الأجل مع رقم الطلب والمنتج إلى boukir.diamond23@gmail.com أو بوسيلة تثبت التوصل. تُتفق طريقة الإرجاع مع خدمة العملاء. يتحمل المستهلك مصاريف الإرجاع إلا في حالة خطأ البائع أو العيب أو عدم المطابقة أو إعلان البائع تحمله لها. تُرد المبالغ المستحقة دون تأخير ووفق الأجل القانوني.'],
      ['13. استثناءات التراجع', 'مع مراعاة القانون، قد يُستثنى من حق التراجع ما صُنع أو قُطع أو خُصص حسب مواصفات العميل، وما لا يمكن بطبيعته إعادة شحنه، والمنتجات سريعة التلف، وبعض الخدمات التي بدأ تنفيذها بموافقته. ويُخبر العميل بالاستثناء المنطبق قبل الطلب.'],
      ['14. المنتجات المعيبة أو غير المطابقة', 'عند استلام منتج متضرر أو خاطئ أو ناقص أو به عيب يشمله الضمان القانوني، يتواصل العميل سريعاً مع خدمة العملاء برقم الطلب وصور إن أمكن. بعد التحقق، يُقترح الحل الذي يقرره القانون بحسب الحالة: الاستبدال أو الإصلاح أو استكمال النقص أو تخفيض السعر أو رد المبلغ. تبقى الضمانات القانونية، ومنها ضمان العيوب الخفية، سارية مستقلة عن أي ضمان تجاري.'],
      ['15. الشكايات وخدمة ما بعد البيع', 'تُرسل الأسئلة والشكايات المتعلقة بالطلبات أو التوصيل أو الإرجاع أو الضمان إلى boukir.diamond23@gmail.com أو إلى أرقام الهاتف أعلاه. يُرجى ذكر رقم الطلب وبيانات الاتصال ووصف المشكلة وإرفاق ما يفيد معالجتها.'],
      ['16. المسؤولية والقوة القاهرة', 'يتحمل البائع مسؤولية حسن تنفيذ التزاماته في حدود القانون، بما في ذلك عمل المتدخلين لحسابه. ولا يتحمل عدم التنفيذ الناتج حصراً عن خطأ العميل أو فعل طرف أجنبي غير متوقع ولا يمكن تجاوزه أو قوة قاهرة وفق القانون المغربي. لا يحرم أي بند العميل من حقوقه الإلزامية.'],
      ['17. الحساب والبيانات الشخصية', 'يقدم العميل بيانات صحيحة ويحافظ على سرية معلومات الدخول ويبلغ عن أي استعمال غير مأذون به. تُعالج بيانات الحساب والطلب والأداء والتوصيل وخدمة ما بعد البيع وفق القانون المغربي رقم 09.08 وسياسة الخصوصية المنشورة بالموقع.'],
      ['18. الملكية الفكرية', 'تحمى العلامات والشعارات والنصوص والصور وقواعد البيانات وعناصر الموقع. ولا تجوز إعادة استعمالها تجارياً دون ترخيص مسبق، مع مراعاة الاستثناءات القانونية.'],
      ['19. الإثبات والأرشفة', 'يمكن اعتماد تأكيدات الطلب وبياناته والأداء والمراسلات المحفوظة بصورة موثوقة كوسائل إثبات وفق القانون المغربي، دون حرمان العميل من أي دليل مقبول. ويمكنه الاطلاع على طلباته في حسابه عند توفر ذلك أو طلب نسخة من خدمة العملاء.'],
      ['20. تعديل الشروط', 'يجوز تحديث هذه الشروط مع بيان تاريخ سريان النسخة الجديدة. ولا تطبق بأثر رجعي على الطلبات المؤكدة سابقاً إلا إذا فرضت قاعدة قانونية إلزامية ذلك.'],
      ['21. استقلالية البنود', 'إذا بطل بند أو تعذر تطبيقه، تبقى باقي البنود نافذة في الحدود التي يسمح بها القانون.'],
      ['22. القانون والنزاعات', 'تخضع هذه الشروط للقانون المغربي. يُدعى العميل أولاً إلى تقديم شكاية مكتوبة لخدمة العملاء سعياً إلى حل ودي. وعند تعذر ذلك، يُرجع إلى الجهات أو المحاكم المختصة وفق القانون، دون حرمان المستهلك من الحماية الإلزامية.'],
      ['23. دخول الشروط حيز التنفيذ', 'تسري هذه الشروط ابتداءً من 23 شتنبر 2026 وتحل محل النسخ السابقة المتعلقة ببيع المنتجات عبر boukirdiamond.com.'],
    ],
  },
  en: {
    title: 'Terms and conditions of sale',
    intro: 'These terms govern purchases of products on boukirdiamond.com, including ordering, payment, delivery, withdrawal and warranties.',
    updated: 'Effective 23 September 2026',
    legalIdentity: 'Seller details',
    labels: ['Legal name', 'Legal form', 'Share capital', 'Commercial register', 'Tax ID', 'ICE', 'Address', 'Email', 'Telephone'],
    sections: [
      ['1. Seller and contact', 'boukirdiamond.com is operated by BOUKIR DIAMOND CONSTRUCTION STORE, a retailer of construction materials, tiles, marble and related products. The seller’s legal and contact details appear above.'],
      ['2. Scope', 'These terms apply to product orders placed through the online store. The version accepted when an order is confirmed applies to that order. Mandatory consumer rights remain unaffected. Unless expressly stated, services supplied by maâlems or other third parties are outside these terms.'],
      ['3. Acceptance', 'Before confirming, customers can review and correct products, quantities, prices, charges, payment method and delivery address. Confirming an order means accepting these terms and the obligation to pay the stated amount, subject to statutory rights.'],
      ['4. Products', 'Available key characteristics, references, dimensions and units are shown on product pages. Images and colours are illustrative; screens, lighting and manufacturing batches may cause small differences. Natural materials may have normal variations in colour or veining, without affecting rights where goods are materially non-conforming. Customers should check suitability and quantities before ordering.'],
      ['5. Prices', 'Prices are in Moroccan dirhams and include applicable taxes unless clearly stated otherwise. Delivery and other charges are shown before confirmation. The amount due is the amount on the confirmed order summary. If an obvious clerical error is identified before fulfilment, the customer may accept the corrected price or cancel and receive a refund. Promotions are subject to their stated period and available stock.'],
      ['6. Ordering and contract', 'Customers select products, review the basket, enter their details, choose delivery or collection and a payment method, then confirm the summary. An acknowledgement states the essential details and order number. Fulfilment depends on availability, correct information and, where applicable, successful payment. An order may be suspended for incomplete details or a serious suspicion of fraud.'],
      ['7. Availability', 'Orders are accepted subject to stock. If an item is unavailable after confirmation, the seller will promptly notify the customer. The customer may expressly accept a substitute, agree to a new date, or cancel the affected item or entire order. Amounts paid for unavailable items will be refunded within the applicable legal period. Substitutions are never imposed without consent.'],
      ['8. Payment', 'Only payment methods displayed at checkout are available; they may depend on the order, area and customer. A bank transfer is received only once funds clear, unless otherwise agreed in writing. Electronic payments are processed by the providers identified to the customer; the seller does not retain complete confidential card details processed directly by them.'],
      ['9. Delivery', 'Delivery is available in served areas of Morocco to the full address provided by the customer. Charges and estimated timing are displayed before confirmation where possible. Unless another period is agreed, fulfilment takes place within the statutory maximum of 30 days after acknowledgement of the order. For a significant delay, the seller will contact the customer to agree a solution preserving legal rights. Customers should inspect parcels on arrival and promptly report damage, errors or shortages, with photographs where possible; lack of a delivery reservation alone does not remove mandatory rights.'],
      ['10. Store collection', 'Where collection is offered, customers select a collection point and wait for a ready notification before visiting. An order number and ID may be requested, or authority for a person collecting on someone else’s behalf. The holding period is communicated with the order or ready notice.'],
      ['11. Cancellation before dispatch', 'Customers may request cancellation before dispatch or before preparation of a personalised item begins by contacting the seller. If dispatch cannot be stopped, the withdrawal and returns rules apply without limiting statutory rights.'],
      ['12. Right of withdrawal', 'Under Moroccan Law 31-08, consumers generally have seven days from receipt to withdraw from a distance purchase without giving a reason or paying a penalty. This may extend to 30 days if required information is not confirmed in writing in the circumstances set by law. The consumer must send a clear notice before the deadline, identifying the order and item, to boukir.diamond23@gmail.com or through a provable communication channel. Return arrangements should be agreed with customer service. Return costs are borne by the consumer unless caused by seller error, defect or non-conformity, or unless the seller has agreed to cover them. Amounts due are refunded without delay within the applicable statutory period.'],
      ['13. Withdrawal exceptions', 'Subject to law, withdrawal may be unavailable for goods made, cut or personalised to customer specifications, goods that by nature cannot be returned, perishable goods, and certain services begun with the consumer’s consent. Any applicable exception is identified before purchase.'],
      ['14. Defective or non-conforming products', 'Customers should promptly report damaged, wrong, incomplete or legally defective goods, with the order number and photographs where possible. After review, the seller will offer the remedy required by law, as appropriate: replacement, repair, completion, price reduction or refund. Statutory warranties, including those for hidden defects, remain in force independently of any commercial warranty.'],
      ['15. Complaints and after-sales service', 'Questions or complaints about orders, delivery, returns or warranties can be sent to boukir.diamond23@gmail.com or the telephone numbers above. Please include the order number, contact details, description and useful evidence.'],
      ['16. Liability and force majeure', 'The seller is responsible for proper performance of its obligations to the extent required by law, including work carried out on its behalf. It is not responsible for non-performance caused exclusively by customer fault, an unforeseeable and unavoidable third party, or force majeure under Moroccan law. Nothing here excludes mandatory customer rights.'],
      ['17. Accounts and personal data', 'Customers must provide accurate details, safeguard login credentials and promptly report unauthorised use. Data needed for accounts, orders, payments, delivery and after-sales service is processed under Moroccan Law 09-08 and the privacy policy published on the site.'],
      ['18. Intellectual property', 'The site’s marks, logos, texts, images, databases and design elements are protected. Commercial reuse without prior authorisation is prohibited, subject to legal exceptions.'],
      ['19. Evidence and records', 'Reliably retained confirmations, order and payment records and correspondence may be used as evidence under Moroccan law, without preventing customers from presenting other admissible evidence. Customers may view orders in their account where available or request a copy from customer service.'],
      ['20. Changes to these terms', 'The seller may update these terms and will state the effective date of each new version. Changes do not apply retrospectively to confirmed orders unless mandatory law requires otherwise.'],
      ['21. Severability', 'If any provision is invalid or unenforceable, the others remain effective to the extent permitted by law.'],
      ['22. Governing law and disputes', 'Moroccan law governs these terms. Customers are invited first to send a written complaint to customer service to seek an amicable solution. Failing that, the competent authority or court is determined by law; mandatory consumer protections remain intact.'],
      ['23. Effective date', 'These terms take effect on 23 September 2026 and supersede earlier versions governing product sales on boukirdiamond.com.'],
    ],
  },
  zh: {
    title: '在线销售条款',
    intro: '本条款适用于在 boukirdiamond.com 购买商品，说明下单、付款、配送、撤销和质量保障规则。',
    updated: '自2026年9月23日起生效',
    legalIdentity: '卖方信息',
    labels: ['法定名称', '法律形式', '注册资本', '商业登记号', '税务识别号', '企业统一识别码 ICE', '地址', '电子邮箱', '电话'],
    sections: [
      ['1. 卖方与联系方式', 'boukirdiamond.com 由 BOUKIR DIAMOND CONSTRUCTION STORE 经营，销售建筑材料、瓷砖、大理石及相关产品。卖方的法定资料和联系方式列于上方。'],
      ['2. 适用范围', '本条款适用于通过网上商店订购的商品。订单确认时客户接受的版本适用于该订单，消费者的强制性法定权利不受影响。除非明确说明，工匠或其他第三方提供的服务不属于本条款范围。'],
      ['3. 接受条款', '确认前，客户可核对并修改商品、数量、价格、费用、付款方式和配送地址。确认订单即表示接受本条款并同意支付显示的金额，但不影响法定权利。'],
      ['4. 商品信息', '商品页面列示可提供的主要特征、编号、尺寸和计量单位。图片与颜色仅供参考，显示设备、光线及生产批次可能造成轻微差异。天然材料可能存在正常的色泽或纹理差异，但这不影响客户针对实质性不符提出主张的权利。下单前请核对商品用途和所需数量。'],
      ['5. 价格', '价格以摩洛哥迪拉姆标示，除非明确说明，已包含适用税费。配送费及其他费用在确认订单前显示。应付金额以客户确认的订单摘要为准。履行前如发现明显笔误，客户可接受更正价格，或取消订单并取回已付款项。促销仅在指定期间和现有库存范围内有效。'],
      ['6. 下单与合同成立', '客户选择商品、核对购物车、填写资料、选择配送或自提及付款方式，然后确认订单摘要。客户会收到包含主要信息和订单号的确认通知。履行取决于库存、资料准确性及必要时付款成功。资料不全或存在严重欺诈疑虑时，订单可暂缓处理。'],
      ['7. 库存情况', '订单以现有库存为限。确认后如商品无法供应，卖方将及时通知客户。客户可明确同意替代商品、接受新的期限，或取消受影响商品或整笔订单。无法供应商品的已付款按法定期限退还；未经同意不得强制替换。'],
      ['8. 付款方式', '实际可用的付款方式以结账页面显示为准，可能因订单、地区和客户而异。除另有书面约定外，银行转账须在款项实际到账后才视为收到。电子付款由向客户标明的服务商处理；卖方不保存由其直接处理的完整机密银行卡资料。'],
      ['9. 配送', '配送范围为摩洛哥境内卖方提供服务的地区，地址须由客户完整填写。费用和预计时间在可行时于确认前显示。除非另有约定，卖方在确认收到订单后法定最长30日内履行。发生重大延误时，卖方将联系客户提出不损害其权利的解决办法。收货时建议核查包裹，及时报告破损、错误或缺件，并尽可能附照片；未当场注明异议本身不消灭客户的强制性权利。'],
      ['10. 门店自提', '如提供自提，客户选择地点并等候备货完成通知后再前往。领取时可能需要订单号及身份证明；代领还可能需要授权。保留期限会在订单或备货通知中告知。'],
      ['11. 发货前取消', '发货前或定制商品开始制作前，客户可联系卖方申请取消。若已无法停止发货，则适用撤销和退货规定，法定权利不受影响。'],
      ['12. 撤销权', '依摩洛哥第31-08号法律，消费者原则上可在收到远程购买商品后7日内无理由、无罚金地撤销。法律规定的情况下，如必要信息未获书面确认，期限可延至30日。客户须在期限内通过 boukir.diamond23@gmail.com 或可证明送达的方式明确通知，并注明订单号和商品。退货安排应与客服协商。退货费用原则上由消费者承担；卖方错误、商品缺陷或不符以及卖方承诺承担费用的情况除外。应退金额将在适用法定期限内及时退还。'],
      ['13. 撤销权例外', '在法律允许范围内，按客户要求制作、切割或定制的商品，依性质无法寄回的商品、易腐商品及经消费者同意已开始的某些服务，可能不适用撤销权。适用的例外会在下单前告知。'],
      ['14. 瑕疵或不符商品', '收到损坏、错误、缺件或存在法定保修范围内缺陷的商品时，客户应尽快提供订单号并联系客户服务，尽可能附照片。核实后，卖方根据法律及具体情况提供更换、维修、补足、降价或退款。包括隐藏瑕疵在内的法定保障不因商业保修而消失。'],
      ['15. 投诉与售后', '有关订单、配送、退货或保修的问题和投诉，可发送至 boukir.diamond23@gmail.com 或拨打上述电话。请提供订单号、联系方式、情况说明和有用的证明材料。'],
      ['16. 责任与不可抗力', '卖方在法律规定范围内对履约负责，包括代表卖方履约的服务商。仅因客户过错、无法预见且无法克服的第三方行为，或摩洛哥法律认可的不可抗力造成的不履行除外。本条款不排除客户的强制性权利。'],
      ['17. 账户与个人数据', '客户须提供准确资料，保护登录凭据，并及时报告未经授权的使用。账户、订单、付款、配送及售后所需数据依摩洛哥第09-08号法律及网站公布的隐私政策处理。'],
      ['18. 知识产权', '网站的商标、标志、文字、图片、数据库和设计元素受保护。除法律例外外，未经事先许可不得用于商业用途。'],
      ['19. 证据与记录', '可靠保存的确认通知、订单和付款记录及通信可依摩洛哥法律作为证据，客户仍可提交其他合法证据。客户可在功能可用时于账户查看订单，或向客服索取副本。'],
      ['20. 条款变更', '卖方可更新本条款并注明新版本生效日期。除强制性法律另有要求外，新条款不追溯适用于已确认订单。'],
      ['21. 条款可分割性', '任何条款无效或不可执行时，其他条款在法律允许范围内继续有效。'],
      ['22. 适用法律与争议', '本条款适用摩洛哥法律。建议客户先向客服提交书面投诉，寻求友好解决。未能解决时，依法由有管辖权的机关或法院处理，消费者的强制性保护不受影响。'],
      ['23. 生效日期', '本条款自2026年9月23日起生效，并取代 boukirdiamond.com 商品销售的所有旧版本。'],
    ],
  },
}
