import brands from './brands.json'

export type CatalogKind = 'categories' | 'marques'
export type CatalogPage = { id: number; slug: string; fr: string; ar: string; adviceFr: string; adviceAr: string; search?: string }
// Slugs are permanent editorial identifiers. Renaming a label must not change them.
export const categories: CatalogPage[] = [
  { id: 73, slug: '73-matieres-de-construction', fr: 'Ciment, sable et matériaux de construction', ar: 'الإسمنت والرمل ومواد البناء', adviceFr: 'Comparez les liants, granulats et matériaux selon leur usage. Vérifiez le conditionnement et les quantités nécessaires avant de préparer votre chantier à Tanger.', adviceAr: 'قارن مواد الربط والرمل ومواد البناء حسب الاستعمال. تحقق من التعبئة والكميات اللازمة قبل تجهيز ورشك في طنجة.' },
  { id: 73, slug: '73-ciment', search: 'ciment', fr: 'Ciment', ar: 'الإسمنت', adviceFr: 'Pour choisir un ciment, comparez sa classe et son conditionnement. Consultez la fiche de la référence pour vérifier son usage et adaptez le dosage aux prescriptions de votre chantier.', adviceAr: 'لاختيار الإسمنت، قارن الصنف وطريقة التعبئة. راجع معلومات المنتج واستعماله المناسب، وحدد الجرعات حسب متطلبات ورشك.' },
  { id: 73, slug: '73-sable', search: 'sable', fr: 'Sable de construction', ar: 'رمل البناء', adviceFr: 'Vérifiez la provenance, la granulométrie et la propreté du sable selon le mortier ou le béton prévu. Confirmez l’unité vendue et les conditions de livraison avant de calculer le volume à commander.', adviceAr: 'تحقق من مصدر الرمل وحجم حبيباته ونظافته حسب الملاط أو الخرسانة المطلوبة. تأكد من وحدة البيع وشروط التوصيل قبل حساب الكمية.' },
  { id: 73, slug: '73-gravette', search: 'gravette', fr: 'Gravette', ar: 'الحصى و gravette', adviceFr: 'Comparez les dimensions des granulats et l’unité de vente. Le choix de la gravette dépend du béton ou de l’aménagement prévu et des spécifications du chantier.', adviceAr: 'قارن مقاسات الحصى ووحدة البيع. يعتمد اختيار الحصى على الخرسانة أو التهيئة المطلوبة ومواصفات الورش.' },
  { id: 75, slug: '75-etancheite-bitume', fr: 'Étanchéité et bitume', ar: 'العزل المائي والبيتومين والزفت', adviceFr: 'Membranes bitumineuses et produits d’imperméabilisation répondent à des supports différents. Comparez épaisseur, finition et mode de pose ; vérifiez la compatibilité du primaire et des accessoires dans la fiche technique.', adviceAr: 'تختلف أغشية البيتومين، المعروف بالزفت، ومنتجات العزل حسب السطح. قارن السمك والتشطيب وطريقة التركيب وتحقق من توافق البرايمر والملحقات في الورقة التقنية.' },
  { id: 48, slug: '48-outillage-carreleur', fr: 'Outillage du carreleur et du marbrier', ar: 'أدوات تركيب وتقطيع البلاط والرخام', adviceFr: 'Cette famille regroupe les équipements de coupe et de pose, les consommables et les accessoires du carreleur. Choisissez selon le format et le matériau à travailler. Pour acheter des carreaux, consultez une référence de revêtement distincte.', adviceAr: 'تضم هذه الفئة أدوات القطع والتركيب والمواد المساعدة وملحقات المعلم. اختر حسب مقاس البلاط والمادة المراد العمل عليها. شراء البلاط نفسه يتطلب منتج تكسية منفصلاً.' },
  { id: 50, slug: '50-colles-carrelage-marbre', fr: 'Colles pour carrelage et marbre', ar: 'لاصق البلاط والرخام', adviceFr: 'Comparez le support, le format des carreaux et l’usage intérieur ou extérieur indiqué par le fabricant. Vérifiez la consommation par mètre carré, le temps ouvert et le conditionnement.', adviceAr: 'قارن نوع السطح ومقاس البلاط والاستعمال الداخلي أو الخارجي حسب تعليمات المصنع. تحقق من الاستهلاك للمتر المربع ووقت العمل والتعبئة.' },
  { id: 76, slug: '76-mastics-joints', fr: 'Mastics et joints', ar: 'المعجون ومواد ملء الفواصل', adviceFr: 'Choisissez le produit selon la largeur du joint, la matière et l’exposition à l’eau. Comparez la couleur et le conditionnement, puis suivez les indications de préparation et de séchage.', adviceAr: 'اختر المنتج حسب عرض الفاصل ونوع المادة والتعرض للماء. قارن اللون والتعبئة واتبع تعليمات التحضير والجفاف.' },
  { id: 52, slug: '52-disques-diamant', fr: 'Disques et outils diamantés', ar: 'أقراص وأدوات القطع الماسية', adviceFr: 'Contrôlez le diamètre, l’alésage et la vitesse maximale compatibles avec votre machine. Le matériau à couper et la coupe à sec ou à eau orientent le choix du disque.', adviceAr: 'تحقق من القطر وفتحة التثبيت والسرعة القصوى المتوافقة مع آلتك. اختر القرص حسب المادة وطريقة القطع الجاف أو بالماء.' },
  { id: 72, slug: '72-peinture', fr: 'Peinture et préparation des surfaces', ar: 'الدهانات وتحضير الأسطح', adviceFr: 'Préparez un support propre et adapté avant la finition. Comparez sous-couches, enduits et peintures selon le support et l’exposition, puis vérifiez le rendement et les temps de séchage.', adviceAr: 'جهز سطحاً نظيفاً ومناسباً قبل التشطيب. قارن الطبقات التحضيرية والمعجون والدهانات حسب السطح والتعرض، وتحقق من المردودية ومدة الجفاف.' },
  { id: 53, slug: '53-plomberie', fr: 'Plomberie et raccords', ar: 'السباكة والأنابيب والوصلات', adviceFr: 'Vérifiez le matériau des conduites, le diamètre et le type de raccord. Les réseaux d’alimentation et d’évacuation exigent des composants adaptés à leur pression et à leur température de service.', adviceAr: 'تحقق من مادة الأنابيب والقطر ونوع الوصلة. تحتاج شبكات التغذية والصرف إلى مكونات مناسبة لضغطها ودرجة حرارة استعمالها.' },
  { id: 36, slug: '36-materiaux-construction', fr: 'Matériaux de construction', ar: 'مواد البناء', adviceFr: 'Retrouvez les familles de matériaux et de mortiers du catalogue. Consultez les unités, dimensions et fiches techniques pour préparer les quantités de votre chantier.', adviceAr: 'تصفح أصناف مواد البناء والملاط في الكتالوج. راجع الوحدات والمقاسات والبيانات التقنية لتحضير كميات ورشك.' },
  { id: 10, slug: '10-outillage', fr: 'Outillage', ar: 'الأدوات والمعدات', adviceFr: 'Choisissez vos outils selon la tâche et la fréquence d’utilisation. Vérifiez les dimensions, la compatibilité des accessoires et les caractéristiques de chaque référence.', adviceAr: 'اختر أدواتك حسب المهمة وتكرار الاستعمال. تحقق من المقاسات وتوافق الملحقات وخصائص كل منتج.' },
]

export function catalogPage(kind: CatalogKind, slug: string): CatalogPage | undefined {
  if (kind === 'categories') return categories.find(c => c.slug === slug)
  const brand = brands.find(b => b.slug === slug)
  if (!brand) return undefined
  return { id: brand.id, slug: brand.slug, fr: brand.name, ar: brand.name,
    adviceFr: `Comparez les références ${brand.name} présentes dans notre catalogue : usage, dimensions, conditionnement et accessoires compatibles. Consultez chaque fiche pour les caractéristiques et le prix affiché.`,
    adviceAr: `قارن منتجات ${brand.name} الموجودة في كتالوجنا حسب الاستعمال والمقاسات والتعبئة والملحقات المتوافقة. راجع كل منتج لمعرفة خصائصه وسعره المعروض.` }
}

export function catalogHref(locale: string, kind: CatalogKind, id: number | string) {
  const page = kind === 'categories' ? categories.find(c => c.id === Number(id) && !c.search) : brands.find(b => b.id === Number(id))
  return page && ['fr', 'ar'].includes(locale) ? `/${locale}/${kind}/${page.slug}` : `/${locale}/shop?${kind === 'categories' ? 'category_id' : 'brand_id'}=${encodeURIComponent(String(id))}`
}
export { brands }
